[tox]
envlist = py{310,311,312,313,314},pep8
skipsdist = True

[testenv]
usedevelop = True
# Customize pip command, add -U to force updates.
install_command = pip install -U {opts} {packages}
deps = -r{toxinidir}/requirements.txt
       -r{toxinidir}/test-requirements.txt
commands =
    pytest {posargs}
    python -c 'import memcache; memcache._doctest()'

[testenv:pep8]
commands = flake8

[testenv:cover]
commands = pytest --cov {posargs}

[flake8]
exclude = venv*,.venv*,.git,.tox,dist,doc,*openstack/common*,*lib/python*,*.egg,.update-venv,build
max-line-length = 119
